version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/carapace-spec
    binary: carapace-spec
  - id: termux
    env:
      - CGO_ENABLED=1
    goos:
      - android
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    main: ./cmd/carapace-spec
    binary: carapace-spec
    gobinary: go-termux
archives:
  - id: default
    builds:
     - default
    format_overrides:
      - goos: windows
        format: zip
  - id: termux
    builds:
      - termux
    name_template: '{{ .Binary }}_{{ .Version }}_termux_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

brews:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    repository:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

scoops:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    repository:
      owner: rsteube
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

aurs:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/carapace-spec-bin.git'

nfpms:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
