version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/carapace-spec
    binary: carapace-spec
    tags:
      - release
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    repository:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

scoops:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    repository:
      owner: rsteube
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

aurs:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/carapace-spec-bin.git'

nfpms:
  -
    description: "define simple completions using a spec file"
    homepage: "https://github.com/rsteube/carapace-spec"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
